### ISSUE TITLE
[Suggestion] Oil Retrogen

### ISSUE THREAD

**Issue by 1skandar** [cout970/Magneticraft-API-and-Issues#59]
While it happens rarely, adding a mod to an existing world does happen and it would be nice to have the option.

**Comment by MechWarrior99** [comment]
Yeah, it would be a good idea to add it in.

**Comment by Cypher121** [comment]
Yeah, if I had any idea how it works.

**Comment by catzs** [comment]
Look at cofhcore's retrogen

**Comment by shobu9** [comment]
@Cypher121 i'll look into it.

**Comment by shobu9** [comment]
@1skandar , @catzs was rigth you can a cofhcore retrogen to retrogen the oil , but ill try to add a command to make your life easier.

**Comment by shobu9** [comment]
Done

**Comment by shobu9** [comment]
Ill add some more setting before closing this.

**Comment by Dead2** [comment]
Another potential cause to need this is starting a server with oil gen disabled in magneticraft due to other mods also generating oil (there is such a thing as too much oil), only to detect that for example magneticraft prospector does not work with other mods oil.
Retrogen for other ores would also be nice, for similar reasons.
